Working
Flick-Picker/full-stack pull request #39
Opened 2023-02-10 22:54 UTC by ali-tab

# Ticket OR Documentation Changes
Replace this with the Jira link and choose the correct title for this section. If `Documentation Change` delete this text instead.

# Description
Please include a small summary of the change (nothing too in-depth as the attached ticket should have more detail)

# Type of change
Delete options that are not relevant. Can be an unnecessary section

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Tests
Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-02-10 23:00 UTC, TAsif requested changes

2023-02-10 23:00 UTC, TAsif commented on src/client/src/router.js
> +    path: '/Preferences',
```suggestion
    path: '/preferences',
```

2023-02-10 23:00 UTC, TAsif commented on src/client/src/pages/Social.jsx
> +<Box>
The formatting on this is funky, Prettier/VS Code has autoformat which you should run - if its not working its fine, when it's merged I'll refactor it

2023-02-10 23:00 UTC, TAsif commented on src/client/src/pages/Social.jsx
> +        </Box>
We shouldn't have navigate from social to create group, it should navigate back home instead and from there a user can go to those pages

2023-02-10 23:00 UTC, TAsif commented on src/client/src/pages/Social.jsx
> +  export default Social;
This page needs an "Add Friends" button before merge, we can deal with "Delete Friend" afterwards

2023-02-11 20:20 UTC, madhi-naga approved these changes

2023-02-11 20:25 UTC, TAsif approved these changes

2023-02-11 20:25 UTC, merged